### PR TITLE
Use an interface for ContactInfo & set unrequested fields to null.

### PR DESCRIPTION
**Pull request by rayankans**
Using an interface would help with issue #19, since we would be able to check if a certain property is supported by the browser. It was also the result of some conversation in #21

### CODE REVIEW

**Comment by beverloo** [comment]
I like that this enables per-property feature detection.

With the default serializer behaviour, the following would happen:

```javascript
const data = await navigator.contacts.select(['tel']);
console.log(JSON.stringify(data));
```

```json
[
  {
    "email": null,
    "name": null,
    "tel": ["+442079460789"]
  }
]
```

That seems rather wasteful, particularly when multiple contacts are being selected, or when more fields may be added to the API. Would it be fair to teach a new `ContactInfo` about the `properties` passed to the `select()` call? It feels a bit hackish.

@domenic wdyt, given that you suggested moving to dictionaries in #5?

**Comment by domenic** [comment]
I still believe that for data that does not have behavior (e.g. methods), a dictionary should be strongly preferred. I do not support moving in this direction.

**Comment by yoavweiss** [comment]
@rayankans - Can you join the WICG in order to appease the IPR bots?

**Comment by rayankans** [comment]
We could potentially have use a non-default `toJSON` implementation that ignores null values, but yeah using a dict seems cleaner at this point.

**Pull request closed without merging**
